init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

branches:
  only:
    - main

install:
  ps: Bootstrap

environment:
  global:
    R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    _R_CHECK_FORCE_SUGGESTS_: false
    USE_RTOOLS: yes
    WARNINGS_ARE_ERRORS:
    R_VERSION: release
    R_ARCH: x64
    R_BUILD_ARGS: --no-build-vignettes 
    R_CHECK_ARGS: --no-manual --ignore-vignettes --as-cran

# This is the minimal set of R packages needed to run "R CMD check" on
# the package.
build_script:
  - R -e install.packages(c('devtools','testthat','MatrixExtra','distr','daarem','Rcpp','RcppParallel','RcppArmadillo','knitr','rmarkdown'),head(.libPaths(),1),'http://cran.wustl.edu')

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
