# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

update_factors_faster_parallel <- function(L_T, FF, M, update_indices, num_iter, line_search, alpha, beta) {
    invisible(.Call('_fastglmpca_update_factors_faster_parallel', PACKAGE = 'fastglmpca', L_T, FF, M, update_indices, num_iter, line_search, alpha, beta))
}

big_exp_crossprod <- function(L, F, n, m) {
    .Call('_fastglmpca_big_exp_crossprod', PACKAGE = 'fastglmpca', L, F, n, m)
}

big_elementwise_mult_crossprod <- function(L, F, nonzero_y, nonzero_y_i_idx, nonzero_y_j_idx, num_nonzero_y) {
    .Call('_fastglmpca_big_elementwise_mult_crossprod', PACKAGE = 'fastglmpca', L, F, nonzero_y, nonzero_y_i_idx, nonzero_y_j_idx, num_nonzero_y)
}

deriv_product <- function(L, F) {
    .Call('_fastglmpca_deriv_product', PACKAGE = 'fastglmpca', L, F)
}

